export const env = {
  PORT: process.env.PORT || 3000,
  APP_BASE_URL: process.env.APP_BASE_URL || 'http://localhost:3000',
  DB: {
    HOST: process.env.DB_HOST,
    PORT: process.env.DB_PORT,
    USERNAME: process.env.DB_USERNAME,
    PASSWORD: process.env.DB_PASSWORD,
    DATABASE: process.env.DB_NAME,
  },
  SALT_KEY: process.env.SALT_KEY,
  SALT_ROUNDS: process.env.SALT_ROUNDS,
  JWT_SECRET: process.env.SECRET_KEY,
  JWT_REFRESH_SECRET: process.env.REFRESH_SECRET_KEY,
  AWS: {
    ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY,
    SECRET_ACCESS_KEY: process.env.AWS_SECRET_KEY,
    REGION: process.env.AWS_REGION || 'us-east-1',
    SES: {
      FROM_EMAIL: process.env.AWS_SES_FROM_EMAIL || 'noreply@neighborly.live',
      REPLY_TO_EMAIL: process.env.AWS_SES_REPLY_TO_EMAIL,
    },
  },
  REDIS: {
    URL: process.env.REDIS_URL || 'redis://localhost:6379',
    HOST: process.env.REDIS_HOST || 'localhost',
    PORT: process.env.REDIS_PORT || 6379,
  },
  GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
  STRIPE: {
    PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    CONNECT_WEBHOOK_SECRET: process.env.STRIPE_CONNECT_WEBHOOK_SECRET,
    CONNECT_CLIENT_ID: process.env.STRIPE_CONNECT_CLIENT_ID,
    ENVIRONMENT: process.env.NODE_ENV || 'development',
    IS_LIVE: process.env.NODE_ENV === 'production',
    PLATFORM_FEE_PERCENTAGE: parseFloat(process.env.STRIPE_PLATFORM_FEE_PERCENTAGE || '2.9'),
    PLATFORM_FEE_FIXED: parseInt(process.env.STRIPE_PLATFORM_FEE_FIXED || '30'),
    PAYOUT_SCHEDULE: process.env.STRIPE_PAYOUT_SCHEDULE || 'manual',
    PAYOUT_DELAY_DAYS: parseInt(process.env.STRIPE_PAYOUT_DELAY_DAYS || '7'),
    DEFAULT_CURRENCY: process.env.STRIPE_DEFAULT_CURRENCY || 'usd',
    REFRESH_URL: process.env.STRIPE_REFRESH_URL || 'http://localhost:3000/stripe/connect/refresh',
    RETURN_URL: process.env.STRIPE_RETURN_URL || 'http://localhost:3000/stripe/connect/return',
  },
  FIREBASE: {
    PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
    PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
  },
  BGC_WEBHOOK_SECRET: process.env.BGC_WEBHOOK_SECRET,
  CRON_JOBS_ENABLED: process.env.CRON_JOBS_ENABLED === 'true',
};
